### ISSUE TITLE
Import Babybear field and Poseidon 2 hash implementation from Plonky3

### ISSUE THREAD

**Issue by ptagl** [telosnetwork/plonky2_goldibear#1]
## Overview
In order to make the **SNARKtor proof aggregation more efficient**, we want to improve the current Plonky2 implementation by "importing" the **Babybear** field from **Plonky3**.
This step would also unlock the possibility of leveraging the **Poseidon 2** implementation available in Plonky3.

Briefly, this activity would allow to use the Plonky2 gates/gadgets system (which is not available on Plonky3) but at the same time upgrade it with a more efficient field (32-bit Babybear) and hash function (Poseidon 2).

It would be beneficial also for use cases involving user proofs generated with Risc0: right now SNARKtor can process these proofs after wrapping them with [Risclonky2](https://github.com/telosnetwork/telos-risclonky2), but after the development of this feature the wrapping wouldn't be needed anymore, making this SNARKtor scenario way faster.

## Acceptance Criteria
- Plonky2 able to generate proofs with the Babybear field and the Poseidon 2 hash function

## Tasks
- [X] Remove the current field/hash structures and traits
- [X] Adapt Plonky2 to use the Plonky3 traits/interfaces
- [x] Adapt the implementation of Babybear and Poseidon 2 to work with the Plonky2 gates/gadgets
- [x] Improve the efficiency of Plonky2 by handling smaller field elements (it currently treats everything as 64 bits, but being Babybear a 32-bits field it would end up wasting memory, potentially affecting performance)
- [x] #8
